# ლექცია #1

## კოდების გაშვებისთვის საჭირო ბიბლიოთეკების იმპორტები

ამ ნოუთბუქის გაშვებამდე არ დაგავიწყდეთ საჭირო დამოკიდებულებების (dependencies) დაინსტალირება, რომლებიც მოცემულია `requirements.txt` ფაილში. მარტივად, ტერმინალიდან გაუშვით:

```bash
pip install -r requirements.txt
```

In [2]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

## ცოტა რამ ხელოვნური ინტელექტის შესახებ

**ხელოვნური ინტელექტი** (**Artificial Intelligence** - **AI**) არის კომპიუტერული მეცნიერების დარგი, რომელიც მიზნად ისახავს ინტელექტუალური ქცევის მქონე მანქანების შექმნას - ადამიანის ინტელექტის სიმულაციას მანქანებში.

**მანქანური სწავლება** (**Machine Learning** - **ML**) არის ხელოვნური ინტელექტის ქვეჯგუფი, რომელიც ფოკუსირებულია ისეთი სისტემების მშენებლობაზე, რომლებსაც შეუძლიათ ისწავლონ მონაცემებიდან და გააკეთონ პროგნოზები ან მიიღონ გადაწყვეტილებები მონაცემების საფუძველზე.

**ღრმა სწავლება** (**Deep Learning** - **DL**) არის ხელოვნური ინტელექტის ქვეჯგუფი, რომელიც ფოკუსირებულია ნეირონული ქსელების შექმნაზე, რომლებიც შთაგონებულია ადამიანის ტვინის სტრუქტურითა და ფუნქციით. ამ ნეირონულ ქსელებს შეუძლიათ ისწავლონ დიდი რაოდენობით მონაცემებიდან და ისინი შეიძლება გამოყენებულ იქნას რთული პრობლემების გადასაჭრელად, როგორიცაა გამოსახულების და მეტყველების ამოცნობა, ბუნებრივი ენის დამუშავება და ა.შ.

**მონაცემთა მეცნიერება** (**Data Science** - **DS**) არის მულტიდისციპლინარული მიდგომა, რომელიც დიდი რაოდენობით მონაცემების გასაანალიზებლად აერთიანებს პრინციპებსა და პრაქტიკებს მათემატიკის, სტატისტიკის, ხელოვნური ინტელექტისა და კომპიუტერული ინჟინერიის სფეროებიდან.

<img src="https://theproposedhekimauniversity.org/wp-content/uploads/2021/11/data-science-in-marketing-post-venn-diagram.jpg" alt="Data Science Diagram" width="600"/>

<img src="https://images.datacamp.com/image/upload/v1685005202/ai_vs_ml_vs_dl_vs_data_science_a919109d75.png" alt="AI ML DL DS Diagram" width="500"/>

**AI-ის 4 ტიპი**:

1. **რეაქტიული AI** მოიცავს სისტემებს მეხსიერების გარეშე, რომლებიც შექმნილია ძალიან კონკრეტული ამოცანის შესასრულებლად. ვინაიდან მათ არ შეუძლიათ წინა შედეგების ან გადაწყვეტილებების გახსენება, ისინი მუშაობენ მხოლოდ ამჟამად ხელმისაწვდომი მონაცემებით. მაგალითად, IBM Deep Blue - ჭადრაკის მოთამაშე სუპერ კომპიუტერი, რომელმაც დაამარცხა გრანდმაისტერი გარი კასპაროვი 1990-იანების მიწურულს საჭადრაკო დაფაზე ფიგურების ანალიზით და თითოეული შესაძლო სვლის შედეგების პროგნოზირებით. Netflix რეკომენდაციის სისტემაც რეაქტიული AI-ია, რეალურად რეკომენდაციები მომდინარეობს მოდელებიდან, რომლებიც ამუშავებენ მონაცემებს ნახვების ისტორიიდან, რომ მომხმარებელს შესთავაზონ კონტენტი, რომელიც მათ ყველაზე მეტად მოეწონებათ.
2. **შეზღუდული მეხსიერების AI**-ს შეუძლია მოერგოს წარსულ გამოცდილებას ან განაახლოს სისტემა ახალი დაკვირვებების ან მონაცემების საფუძველზე. ხშირად, განახლების რაოდენობა შეზღუდულია (სწორედ აქედან გამომდინარეობს სახელი) და მეხსიერების ხანგრძლივობა შედარებით მოკლეა. მაგალითად, ვირტუალური ასისტენტები, ჩატბოტები, თვითვმართვადი მანქანები.
3. **თეორიული მეხსიერების AI** სრულად ადაპტირებადია და აქვს წარსული გამოცდილების სწავლისა და შენარჩუნების ფართო უნარი. ამ ტიპის ხელოვნური ინტელექტი მოიცავს მოწინავე ჩატ-ბოტებს, რომლებსაც შეუძლიათ გაიარონ ტურინგის ტესტი და მოატყუონ ადამიანი და დააჯერონ, რომ AI ადამიანი იყო. მიუხედავად იმისა, რომ ეს ვერსია მოწინავე და შთამბეჭდავია, ეს AI არ არის თვითშეგნებული.
4. **თვითშეგნებული AI**, როგორც სახელიდან ჩანს, არიან მგრძნობიარენი და აცნობიერებენ საკუთარ არსებობას.

** **ტურინგის ტესტი**: "ადამიანი ურთიერთქმედებს ერთ კომპიუტერსა და ერთ ადამიანთან. კითხვებზე პასუხის გათვალისწინებით მან უნდა განსაზღვროს, ვის ესაუბრება: ადამიანს თუ კომპიუტერულ პროგრამას. კომპიუტერული პროგრამის მიზანია ადამიანი შეცდომაში შეიყვანოს და არასწორი არჩევანი გააკეთებინოს".


ML-ის კონტექსტში, **მოდელი** არის რეალური სამყაროს პროცესის ან სისტემის მათემატიკური წარმოდგენა, რომლის გაგება ან რომელზე დაყრდნობითაც პროგნოზების გაკეთება გვინდა. მოდელი იქმნება მონაცემთა გამოყენებით, რომელიც შეიცავს ინფორმაციას პროცესის ან სისტემის შესახებ. ML მოდელის მიზანია ისწავლოს შაბლონები და კავშირები მონაცემებში, რომლებიც შეიძლება გამოყენებულ იქნას პროგნოზების ან გადაწყვეტილების მისაღებად.

**ალგორითმი** არის წესების ან ინსტრუქციების ერთობლიობა, რომელსაც კომპიუტერი მიჰყვება პრობლემის გადასაჭრელად. ML-ის კონტექსტში, ალგორითმი გამოიყენება მონაცემთა ბაზაზე მოდელის მოსამზადებლად. ალგორითმი სწავლობს მონაცემებიდან მოდელის პარამეტრების კორექტირებით, რათა მინიმუმამდე დაიყვანოს დანაკარგის ფუნქცია, რომელიც ზომავს რამდენად კარგად მუშაობს მოდელი. ML ალგორითმები შედგენილია სტატისტიკის, კალკულუსისა და წრფივი ალგებრის საფუძველზე.

ML ალგორითმის გაშვების პროცესს მონაცემთა ბაზაზე (სასწავლო მონაცემებზე) და ალგორითმის ოპტიმიზაციას გარკვეული შაბლონების ან შედეგების მოსაძებნად ეწოდება მოდელის **ტრენინგი**. 

ML-ის ტიპები:

1. **Supervised learning**: თითოეულ მონაცემს გააჩნია თავისი შესაბამისი ეტიკეტი (**label**) და მოდელმა მონაცემებზე დაყრდნობით უნდა ისწავლოს ამ ეტიკეტის დადგენა.

<img src="https://miro.medium.com/v2/resize:fit:1400/1*_YfYURermogYfTxYUEhXNA.jpeg" alt="Supervised Learning" width="500"/>

2. **Unsupervised learning**: მონაცემებს არ გააჩნია ეტიკეტები.

![Unsupervised Learning](https://miro.medium.com/v2/resize:fit:433/1*Iihw0V-r0raMMtcDTFGGQA.png)

3. **Reinforcement learning**: აგენტი (სუბიექტი, რომელიც სწავლობს და იღებს გადაწყვეტილებებს) სწავლობს გადაწყვეტილებების მიღებას გარემოსთან ურთიერთქმედებით. აგენტი მისი ქმედებებისთვის იღებს უკუკავშირს გარემოსგან ჯილდოს ან ჯარიმების სახით. აგენტი სწავლობს მიზნის მიღწევას ან ჯილდოს მაქსიმიზაციას ცდისა და შეცდომის (trial and error) გზით, მკაფიო ინსტრუქციების გარეშე, თუ როგორ უნდა შეასრულოს დავალება.

<img src="https://www.kdnuggets.com/wp-content/uploads/awan_reinforcement_learning_newbies_1.png" alt="Reinforcement learning" width="500"/>

**მოდელის ტრენინგის მაგალითი supervised learning-ში**:

გვაქვს ეტიკეტიანი მონაცემები, რომლებიც უნდა დაიყოს სატრენინგო და სატესტო მონაცემებად. შესაბამისად, სატრენინგო მონაცემების გამოყენებით ხდება ტრენინგი, ხოლო სატესტო მონაცემები გამოიყენება დატრენინგებული მოდელის შესაფასებლად.

![Labeled Data](https://developers.google.com/static/machine-learning/intro-to-ml/images/labeled_example.png)

ტრენინგი:

1. მოდელი იღებს ერთ ეტიკეტირებულ მაგალითს და იძლევა პროგნოზს.

![Prediction](https://developers.google.com/static/machine-learning/intro-to-ml/images/training-a-model-01.png)

2. მოდელი ადარებს მის პროგნოზირებულ მნიშვნელობას რეალურ მნიშვნელობას და აახლებს მის გადაწყვეტის გზას.

<img src="https://developers.google.com/static/machine-learning/intro-to-ml/images/training-a-model-02.png" alt="Comparing" width="600"/>

3. მოდელი იმეორებს ამ პროცესს მონაცემთა ნაკრების თითოეული მაგალითისთვის.

![Training](https://developers.google.com/static/machine-learning/intro-to-ml/images/training-a-model-03.png)

შეფასება:

როდესაც ჩვენ ვაფასებთ მოდელს, მას ვაძლევთ მხოლოდ მონაცემთა მახასიათებლებს (**features**). შემდეგ ჩვენ ვადარებთ მოდელის პროგნოზებს ეტიკეტის ნამდვილ მნიშვნელობებს.

<img src="https://developers.google.com/static/machine-learning/intro-to-ml/images/evaluating-a-model.png" alt="Evaluating" width="600"/>

## ვექტორები

ორიენტირებულ მონაკვეთს, რომლისთვისაც დასახელებულია სათავე და ბოლო წერტილები, ვექტორი ეწოდება.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vector_from_A_to_B.svg/1200px-Vector_from_A_to_B.svg.png" alt="Vector" width="500"/>

ვექტორი, რომლის სათავე A წერტილია, ხოლო ბოლო B წერტილია, აღინიშნება $\overrightarrow{AB}$ სიმბოლოთი.

ვექტორს, რომლის სათავე და ბოლო წერტილები ერთმანეთს ემთხვევიან, ნულოვანი ვექტორი ეწოდება და მას მიმართულება არ გააჩნია. ნულოვანი ვექტორი ასე აღინიშნება - $\vec{0}$.

A და B წერტილებს შორის მანძილს $\overrightarrow{AB}$ ვექტორის სიგრძე ეწოდება და აღინიშნება $\|\overrightarrow{AB}\|$ სიმბოლოთი. ნულოვანი ვექტორის სიგრძე 0-ია. ვექტორს, რომლის სიგრძე 1-ის ტოლია, ერთეულოვანი ვექტორი ეწოდება.

ვექტორის სიგრძის გამოსათვლელი ფორმულაა $\sqrt{x^2+y^2}$.

![Length of a vector](https://cdn.kastatic.org/ka-perseus-images/9150ff25c140f6abd6da845d59533880324158a9.png)


In [3]:
a = np.array([3, 4])

size = np.linalg.norm(a)
size

5.0

ორ ვექტორს **ტოლი** ეწოდება, თუ მათ (სათავის ანუ მოდების წერტილისგან დამოუკიდებლად) ტოლი სიგრძე და ერთი და იგივე მიმართულება აქვთ.

![Equal Vectors](https://onlinemschool.com/pictures/vector/vector_equality.png)

ორ ვექტორს ეწოდება **კოლინეარული**, თუ ისინი ერთი და იგივე წრფის პარალელურია, და **კომპლანარული**, თუ ერთი და იგივე სიბრტყის პარალელურია.

![Collinear and Coplanar Vectors](https://tuitionphysics.com/wp-content/uploads/2020/05/scalar-and-vector-quantities-what-exactly-are-they.jpg)

### ვექტორების შეკრება

$$\vec{a} = (x_1; y_1)$$

$$\vec{b} = (x_2; y_2)$$

$$\vec{a} + \vec{b} = (x_1 + x_2; y_1 + y_2)$$

**ვექტორების შეკრების სამკუთხედის და პარალელოგრამის წესი**:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Vector_addition.svg/1920px-Vector_addition.svg.png" alt="Addition of Vectors" width="600"/>

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum_vector = a + b
sum_vector

array([5, 7, 9])

### ვექტორების გამოკლება

$$\vec{a} = (x_1; y_1)$$

$$\vec{b} = (x_2; y_2)$$

$$\vec{a} - \vec{b} = (x_1 - x_2; y_1 - y_2)$$

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Vector_subtraction.svg/1280px-Vector_subtraction.svg.png" alt="Subtraction of Vectors" width="600"/>

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

difference_vector = a - b
difference_vector

array([-3, -3, -3])

### ვექტორის სკალარზე ნამრავლი

$$\vec{a} = (x; y)$$

$$\lambda \cdot \vec{a}=(\lambda x; \lambda  y)$$

$$0 \cdot \vec{a} = \vec{0}$$

$$(-1) \cdot \vec{a} = -\vec{a}$$

$$\lambda \cdot \vec{0} = \vec{0}$$

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Scalar_multiplication_by_r%3D3.svg/1920px-Scalar_multiplication_by_r%3D3.svg.png" alt="Scalar Multiplication by 3" width="600"/>

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Scalar_multiplication_of_vectors2.svg/1920px-Scalar_multiplication_of_vectors2.svg.png" alt="Scalar Multiplication" width="600"/>

In [6]:
a = np.array([1, 2, 3])
scalar = 5

product_vector = scalar * a
product_vector

array([ 5, 10, 15])

### Dot product

კუთხე $\vec{a}$ და $\vec{b}$ ვექტორებს შორის ეწოდება იმ უმცირეს კუთხეს, რომლითაც უნდა მოვატრიალოთ ერთ-ერთი მათგანი რომ მეორეს დაემთხვეს.

![Angle Between Vectors](https://onlinemschool.com/pictures/vector/vector_angl.png)

$$\vec{a} \cdot \vec{b} = \| \vec{a} \| \| \vec{b} \| \cos(\theta)$$

$$\cos(\theta) = \dfrac{\vec{a} \cdot \vec{b}}{\| \vec{a} \| \| \vec{b} \|}$$

$$\vec{a} = (a_1, a_2, a_3)$$

$$\vec{b} = (b_1, b_2, b_3)$$

$$\vec{a} \cdot \vec{b} = a_1b_1 + a_2b_2 + a_3b_3$$

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
dot_product

32

### Cross product

$$\vec{a} \times \vec{b} = \vec{c}$$

$$\| \vec{c} \| = \| \vec{a} \| \| \vec{b} \| \sin(\theta)$$

$$\vec{a} = (a_1, a_2, a_3)$$

$$\vec{b} = (b_1, b_2, b_3)$$

$$
\vec{a} \times \vec{b} = \begin{bmatrix}
a_2b_3 - a_3b_2 \\ \\
a_3b_1 - a_1b_3 \\ \\
a_1b_2 - a_2b_1
\end{bmatrix}
$$

![Cross Product](https://www.sharetechnote.com/image/EngMath_Matrix_CrossProduct_01.png)

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

cross_product = np.cross(a, b)
cross_product

array([-3,  6, -3])

### 2 ვექტორს შორის მანძილი

$$d(\vec{a}, \vec{b}) = \| \vec{a} - \vec{b} \| = \sqrt{(a_1 - b_1)^2 + (a_2 - b_2)^2 + ... + (a_n - b_n)^2}$$

$$\vec{a} = (2, 3, 4, 2)$$
$$\vec{b} = (1, -2, 1, 3)$$

$$d(\vec{a}, \vec{b}) = \sqrt{(2 - 1)^2 + (3 - (-2))^2  + (4 - 1)^2 + (2 - 3)^2} = \sqrt{1 + 25 + 9 + 1} = \sqrt{36} = 6$$


In [9]:
a = np.array([2, 3, 4, 2])
b = np.array([1, -2, 1, 3])

euclidean_distance = np.linalg.norm(a - b)
euclidean_distance

6.0

### ვექტორების ნორმები

#### ნულოვანი რიგის ნორმა

არანულოვან ელემენტთა რაოდენობა ვექტორში

In [10]:
a = np.array([1, -2, 3, 0, -9, 2, 0])
norm_0 = np.linalg.norm(a, 0)
norm_0

5.0

#### პირველი ნორმა

ელემენტების აბსოლუტური მნიშვნელობების ჯამი

$$\| x \| _1 = \sum^{n}_{i=1} |x_i|$$

In [11]:
a = np.array([-1, -2, 3])
norm_1 = np.linalg.norm(a, 1)
norm_1

6.0

#### მეორე ნორმა

ვექტორის სიგრძე

$$\| x \| _2 = \sqrt{x_1^2 + x_2^2 + ... + x_n^2}$$

In [12]:
a = np.array([1, 2, 3])
norm_2 = np.linalg.norm(a, 2)
norm_2

3.7416573867739413

#### უსასრულობა ნორმა

ელემენტების აბსოლუტური მნიშვნელობებიდან მაქსიმალური

$$\| x \| _\infty = \max_{i} | x_i |$$

In [13]:
a = np.array([1, 2, -3])
norm_inf = np.linalg.norm(a, np.inf)
norm_inf

3.0

#### P ნორმა

$$\| x \| _p = (\sum^{n}_{i=1} |x_i|^p)^ \frac{1}{p}$$

$$\| x \| _p = \sqrt[p]{|x_1|^p + |x_2|^p + ... + |x_n|^p}$$

In [14]:
a = np.array([1, 2, -3])
p = 5
norm_p = np.linalg.norm(a, p)
norm_p

3.077384885394063

## უახლოესი მეზობლის კლასიფიკატორი

უახლოესი მეზობლის კლასიფიკატორი უმარტივესი კლასიფიკატორია. როდესაც ახალი ნივთის კლასიფიკაცია გვსურს, ის პოულობს სასწავლო მონაცემთა ერთეულს, რომელიც ყველაზე მეტად ჰგავს ახალ ელემენტს და გამოაქვს მისი ეტიკეტი.

![Nearest Neighbor](https://course.elementsofai.com/static/4_2_nearest-neighbor-graph-ff89ea77c8009dafc4966c0cca4df4dc.svg)

ზემოთ მოცემულ დიაგრამაში მოცემულია ტრენინგის მონაცემები, რომელთაგან ზოგიერთი ეკუთვნის ერთ კლასს (მწვანე) და ზოგიერთი მეორე მეორე კლასს (ლურჯი). გარდა ამისა, არის სატესტო მონაცემების ორი ელემენტი, ვარსკვლავები, რომელთა კლასიფიკაციას ვაპირებთ უახლოესი მეზობლის მეთოდით.

ორივე სატესტო ელემენტი კლასიფიცირებულია როგორც "მწვანე", რადგან მათი უახლოესი მეზობლები ორივე მწვანეა.

**რა იგულისხმება, როცა ვამბობთ "უახლოესი"?**

საინტერესო კითხვა, რომელიც დაკავშირებულია (სხვა საკითხებთან ერთად) უახლოესი მეზობლის კლასიფიკატორთან არის ინსტანსებს/წერტილებს შორის მანძილის ან მსგავსების განსაზღვრა. ზემოთ მოყვანილ დიაგრამაში ნაგულისხმევია, რომ გამოყენებულია სტანდარტული გეომეტრიული მანძილი, რომელსაც ტექნიკურ ენაზე უწოდებენ ევკლიდურ მანძილს. ეს უბრალოდ ნიშნავს, რომ თუ წერტილები დახატულია ფურცელზე (ან ნაჩვენებია თქვენს ეკრანზე), შეგიძლიათ გაზომოთ მანძილი ნებისმიერ ორ ელემენტს შორის ძაფის პირდაპირ ერთიდან მეორე წერტილამდე გადაჭიმვით და სიგრძის გაზომვით.

გეომეტრიული მანძილის გამოყენება უახლოესი ელემენტის დასადგენად შეიძლება ყოველთვის არ იყოს გონივრული ან თუნდაც შესაძლებელი: მონაცემის ტიპი შეიძლება იყოს ტექსტი, სადაც გაუგებარია ელემენტების გეომეტრიული გამოსახულება და მათ შორის მანძილის გაზომვის გზა. ამიტომ ყოველთვის მონაცემის ტიპზე დაყრდნობით ხდება მანძილის მეტრიკის არჩევა.

**რეკომენდაციის სისტემის უმარტივესი ამოცანა**:

მოცემულია 6 მომხმარებლის მონაცემები. თითოეული მომხმარებლისთვის ჩვენ გვაქვს ბოლოდროინდელი საყიდლების ისტორია, რომელიც შედგება 4 ნივთისგან. ასევე გვაქვს ამ 4 ნივთის შემდგომ შეძენილი მე-5 ნივთიც.

| User   | Shopping History #1         | Shopping History #2 | Shopping History #3         | Shopping History #4 | Purchase (#5)   |
| ------ | --------------------------- | ------------------- | --------------------------- | ------------------- | --------------- |
| Sanni  | boxing gloves               | Moby Dick (novel)   | headphones                  | sunglasses          | coffee beans    |
| Jouni  | t-shirt                     | coffee beans        | coffee maker                | coffee beans        | coffee beans    |
| Janina | sunglasses                  | sneakers            | t-shirt                     | sneakers            | ragg wool socks |
| Henrik | 2001: A Space Odyssey (dvd) | headphones          | t-shirt                     | boxing gloves       | flip flops      |
| Ville  | t-shirt                     | flip flops          | sunglasses                  | Moby Dick (novel)   | sunscreen       |
| Teemu  | Moby Dick (novel)           | coffee beans        | 2001: A Space Odyssey (dvd) | headphones          | coffee beans    |

უახლოესი მეზობლის მეთოდის გამოსაყენებლად უნდა განვსაზღვროთ რას ვგულისხმობთ "უახლოესში". ეს შეიძლება გაკეთდეს სხვადასხვა გზით, რომელთაგან ზოგი უკეთესად მუშაობს, ვიდრე სხვები. მოდით სიმარტივისთვის გამოვიყენოთ საყიდლების ისტორია, სადაც დავითვლით თუ რამდენი ერთი და იგივე ნივთი შეიძინა ორივე მომხმარებელმა.

მაგალითად, მომხმარებლებმა Ville-მ და Henrik-მა ორივემ იყიდეს მაისური, ამიტომ მათი მსგავსება არის 1. გაითვალისწინეთ, რომ flip flops არ ითვლება, რადგან მსგავსების გამოთვლისას ჩვენ არ ჩავთვლით უახლეს შენაძენს - ის სხვა მიზნისთვის არის განკუთვნილი.

ჩვენი ამოცანაა ვიწინასწარმეტყველოთ Travis-ის შემდეგი შესყიდვა, რომლის ისტორიაც ასე გამოიყურება:

| User   | Shopping History #1 | Shopping History #2 | Shopping History #3 | Shopping History #4 | Purchase (#5) |
| ------ | ------------------- | ------------------- | ------------------- | ------------------- | ------------- |
| Travis | green tea           | t-shirt             | sunglasses          | flip flops          | ?             |

<details>
  <summary>1. რომელი მომხმარებელია ყველაზე მეტად Travis-ის მსგავსი?</summary>
  Ville (3 მსგავსებით)
</details>

<details>
  <summary>2. რომელი ნივთის შესყიდვა იქნება მოსალოდნელი Travis-სგან?</summary>
  sunscreen (ვინაიდან Ville-ის ბოლო შესყიდვა იყო sunscreen, ჩვენ მას Travis-საც ვურჩევთ)
</details>

### K უახლოესი მეზობელი (K-Nearest Neighbor - KNN)

K უახლოესი მეზობლის ალგორითმი ერთ-ერთი ყველაზე მარტივი ალგორითმია, რომელიც გამოიყენება მანქანურ სწავლებაში. იგი უზრუნველყოფს მონაცემის მიკუთვნებას იმ კლასისათვის, რომელთანაც უფრო ახლოსაა მონაცემი k მეზობელი კლასებიდან ნიშან-თვისებათა მრავალგანზომილებიან სივრცეში. დასწავლის პროცესში უბრალოდ იმახსოვრებს ყველა ვექტორს და მათ შესაბამის კლასს, ხოლო რეალურ მონაცემებთან მუშაობისას, კლასების გამოცნობისათვის, იგი გამოითვლის ორ ვექტორს შორის მანძილს და k-ს (მეზობელი კლასების რაოდენობა) განსაზღვრის შემდეგ ობიექტს მიაკუთვნებს იმ კლასს, რომელიც ყველაზე უფრო ახლოსაა.

<img src="https://miro.medium.com/v2/resize:fit:4800/format:webp/0*34SajbTO2C5Lvigs.png" alt="KNN" width="600"/>

In [15]:
def get_neighbors(train, test_row, num_neighbors):
    # თითოეულისთვის მანძილის გამოთვლა
    distances = []
    for train_row in train:
        dist = np.linalg.norm(test_row[:2] - train_row[:2])
        distances.append((train_row, dist))

    # სიის დასორტირება მანძილის მიხედვით ზრდადობით
    distances.sort(key=lambda x: x[1])

    # უახლოესი num_neighbors რაოდენობის მეზობლის ამორჩევა
    neighbors = []
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])

    return neighbors


def predict(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    # მეზობლებს შორის ყველაზე ხშირად წარმოდგენილი კლასის არჩევა
    prediction = max(set(output_values), key=output_values.count)

    return prediction


data = np.array(
    [
        [2.7810836, 2.550537003, 0],
        [1.465489372, 2.362125076, 0],
        [3.396561688, 4.400293529, 0],
        [1.38807019, 1.850220317, 0],
        [3.06407232, 3.005305973, 0],
        [7.627531214, 2.759262235, 1],
        [5.332441248, 2.088626775, 1],
        [6.922596716, 1.77106367, 1],
        [8.675418651, -0.242068655, 1],
        [7.673756466, 3.508563011, 1],
    ]
)
test_data = np.array([0.12341, 1.2789, 0])

prediction = predict(train=data, test_row=test_data, num_neighbors=3)
print(f"Expected {test_data[-1]}, Got {prediction}")

Expected 0.0, Got 0.0


## კოსინუსის მსგავსება

Term Frequency - Inverse Document Frequency (TF-IDF)

[wikipedia-ის სტატია TF-IDF-ის შესახებ](https://en.wikipedia.org/wiki/Tf%E2%80%93idf)

[ვიდეო TF-IDF-ის შესახებ](https://youtu.be/OymqCnh-APA)

In [16]:
sentence_1 = "Quick brown fox jumps over the lazy dog."
sentence_2 = "Quick brown dog outpaces the quick fox."

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([sentence_1, sentence_2])

cosine_sim = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1])
cosine_sim

array([[0.57472096]])

In [17]:
vectorizer.get_feature_names_out()

array(['brown', 'dog', 'fox', 'jumps', 'lazy', 'outpaces', 'over',
       'quick', 'the'], dtype=object)

In [18]:
tfidf_matrix.todense()

matrix([[0.30253071, 0.30253071, 0.30253071, 0.42519636, 0.42519636,
         0.        , 0.42519636, 0.30253071, 0.30253071],
        [0.31661852, 0.31661852, 0.31661852, 0.        , 0.        ,
         0.44499628, 0.        , 0.63323704, 0.31661852]])